"""add original_isbn to books

Revision ID: dd09c96783e4
Revises: 4b3dc700b828
Create Date: 2026-09-20 02:38:28.899413

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd09c96783e4'
down_revision: Union[str, Sequence[str], None] = '4b3dc700b828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('original_isbn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'original_isbn')
    # ### end Alembic commands ###
