"""add keyword tag

Revision ID: 073006d27ad0
Revises: 4cd4eeffb00e
Create Date: 2026-06-18 23:01:23.085230

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '073006d27ad0'
down_revision: Union[str, Sequence[str], None] = '4cd4eeffb00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_tags_keyword'), 'keyword_tags', ['keyword'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_tags_keyword'), table_name='keyword_tags')
    op.drop_table('keyword_tags')
    # ### end Alembic commands ###
