"""add edition_groups

Revision ID: 4b3dc700b828
Revises: 073006d27ad0
Create Date: 2026-06-28 01:06:34.650071

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b3dc700b828'
down_revision: Union[str, Sequence[str], None] = '073006d27ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edition_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edition_groups_name'), 'edition_groups', ['name'], unique=False)
    with op.batch_alter_table('books') as batch_op:
        batch_op.add_column(sa.Column('edition_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_books_edition_group_id'), ['edition_group_id'], unique=False)
        batch_op.create_foreign_key('book_edition_group_fk', 'edition_groups', ['edition_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books') as batch_op:
        batch_op.drop_constraint('book_edition_group_fk', type_='foreignkey')
        batch_op.drop_index(op.f('ix_books_edition_group_id'))
        batch_op.drop_column('edition_group_id')
    op.drop_index(op.f('ix_edition_groups_name'), table_name='edition_groups')
    op.drop_table('edition_groups')
    # ### end Alembic commands ###
