"""add manually_updated_fields to books

Revision ID: f9209efe522c
Revises: dd09c96783e4
Create Date: 2026-09-20 02:54:28.651236

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9209efe522c'
down_revision: Union[str, Sequence[str], None] = 'dd09c96783e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('manually_updated_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'manually_updated_fields')
    # ### end Alembic commands ###
