"""add file_path to book

Revision ID: 4cd4eeffb00e
Revises: 3dfaf07c90d2
Create Date: 2026-06-17 23:43:01.274886

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4cd4eeffb00e'
down_revision: Union[str, Sequence[str], None] = '3dfaf07c90d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'file_path')
    # ### end Alembic commands ###
