"""initial schema

Revision ID: 3dfaf07c90d2
Revises: 
Create Date: 2026-06-16 19:33:56.218778

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3dfaf07c90d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.create_table('book_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_series_name'), 'book_series', ['name'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_table('languages',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('amazon_url', sa.String(), nullable=True),
    sa.Column('goodreads_url', sa.String(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name='book_collections_fk'),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], name='book_publishers_fk'),
    sa.ForeignKeyConstraint(['series_id'], ['book_series.id'], name='book_series_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_checksum'), 'books', ['checksum'], unique=False)
    op.create_index(op.f('ix_books_collection_id'), 'books', ['collection_id'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_index(op.f('ix_books_language_code'), 'books', ['language_code'], unique=False)
    op.create_index(op.f('ix_books_publisher_id'), 'books', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_books_series_id'), 'books', ['series_id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('books_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('books_tags',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_tags')
    op.drop_table('books_authors')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_series_id'), table_name='books')
    op.drop_index(op.f('ix_books_publisher_id'), table_name='books')
    op.drop_index(op.f('ix_books_language_code'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_collection_id'), table_name='books')
    op.drop_index(op.f('ix_books_checksum'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_table('languages')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_book_series_name'), table_name='book_series')
    op.drop_table('book_series')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
